version: '3.5'
services:
  scraping:
    container_name: shalion-scrape
    restart: unless-stopped
    build:
      context: .
      shm_size: '2gb'
    shm_size: '2gb'
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.0.8
    restart: unless-stopped
    hostname: mongodb
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: scrape
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
    driver: local