version: '3.5'
services:
  scraping:
    container_name: shalion-scrape
    restart: unless-stopped
    command: python3 /app/src/server.py
    build:
      context: .
      shm_size: '2gb'
    shm_size: '2gb'
    ports:
      - "8080:8080"
  
  mongodb:
    image: mongo:4.0.8
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopass
      MONGO_INITDB_DATABASE: mongoscrape
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
    driver: local